const ANOMALIES = "ANOMALIES"

const LABEL = "LABEL"

const HISTORY_DATA ="HISTORY_DATA"

const EDIT_HISTORY="EDIT_HISTORY"

const SESSION ="SESSION"

const EIGHT_DAYS_DATA="EIGHT_DAYS_DATA"

const REALTIME_OVERVIEW="REALTIME_OVERVIEW"

const CHILLER = "CHILLER"
const PLANT = "PLANT"

const CHILLER_LAST_UPDATED = "CHILLER_LAST_UPDATED"
const PLANT_LAST_UPDATED = "PLANT_LAST_UPDATED"

const TEST ="TEST"

const PREVIOUS_DATA="PREVIOUS_DATA"

const RUNNING_SCHEDULER = "RUNNING_SCHEDULER"



module.exports={
    ANOMALIES,HISTORY_DATA,LABEL,EDIT_HISTORY,SESSION,EIGHT_DAYS_DATA,
    REALTIME_OVERVIEW, CHILLER, CHILLER_LAST_UPDATED, PLANT, PLANT_LAST_UPDATED,
    TEST,PREVIOUS_DATA,
    RUNNING_SCHEDULER
}