const data =
     [
      {
        "dataType": "PLANT_ACTIVITY_COUNT",
        "deviceType": null,
        "deviceName": null,
        "message": "Plant has more than 10 activities per day",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": null,
        "value1": 10,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "PLANT_EFFICIENCY",
        "deviceType": null,
        "deviceName": null,
        "message": "Plant Efficiency is less than 0.4kW/RT, more than 1kW/RT",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": null,
        "value1": 0.5,
        "value2": 1,
        "consecutiveMinute": 1
      },
      {
        "dataType": "PLANT_FLOW_RATE",
        "deviceType": null,
        "deviceName": null,
        "message": "Flow rate is less than 100",
        "operator": "LESS_THAN",
        "priority": "INFO",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": null,
        "value1": 100,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "ACTIVITY_COUNT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller1",
        "message": "Chiller 1 has more than 6 activities per day",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 6,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "DATA_QUALITY",
        "deviceType": "CHILLER",
        "deviceName": "Chiller1",
        "message": "Chiller 1 Data Rate is below 97%",
        "operator": "LESS_THAN",
        "priority": "LOW",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 97,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EFFICIENCY",
        "deviceType": "CHILLER",
        "deviceName": "Chiller1",
        "message": "Chiller 1 , Efficiency is less than 0.4kW/RT, more than 1kW/RT",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 0.4,
        "value2": 1,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_DELTA",
        "deviceType": "CHILLER",
        "deviceName": "Chiller 1",
        "message": "Chiller 1 , Delta Temp  is more than  7°C",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 7,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_DELTA",
        "deviceType": "CHILLER",
        "deviceName": "Chiller1",
        "message": "Chiller 1 , Delta Temp  is less than  2°C",
        "operator": "LESS_THAN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 2,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_INPUT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller1",
        "message": "Chiller 1 , Eva Input is less than 5°C, more than 20°C",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 5,
        "value2": 20,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_OUTPUT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller1",
        "message": "Chiller 1 , Eva Output is less than 5°C, more than 20°C",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 5,
        "value2": 20,
        "consecutiveMinute": 1
      },
      {
        "dataType": "POWER_LOADING",
        "deviceType": "CHILLER",
        "deviceName": "Chiller1",
        "message": "Chiller 1, Power Loading is less than 30%",
        "operator": "LESS_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 30,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "ACTIVITY_COUNT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller2",
        "message": "Chiller 2 has more than 6 activities per day",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 44,
        "value1": 6,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "DATA_QUALITY",
        "deviceType": "CHILLER",
        "deviceName": "Chiller2",
        "message": "Chiller 2 Data Rate is below 97%",
        "operator": "LESS_THAN",
        "priority": "LOW",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 44,
        "value1": 97,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EFFICIENCY",
        "deviceType": "CHILLER",
        "deviceName": "Chiller2",
        "message": "Chiller 2 , Efficiency is less than 0.4kW/RT, more than 1kW/RT",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 44,
        "value1": 0.4,
        "value2": 1,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_DELTA",
        "deviceType": "CHILLER",
        "deviceName": "Chiller 2",
        "message": "Chiller 2 , Delta Temp  is more than  7°C",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 44,
        "value1": 7,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_DELTA",
        "deviceType": "CHILLER",
        "deviceName": "Chiller2",
        "message": "Chiller 2 , Delta Temp  is less than  2°C",
        "operator": "LESS_THAN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 44,
        "value1": 2,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_INPUT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller2",
        "message": "Chiller 2 , Eva Input is less than 5°C, more than 20°C",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 44,
        "value1": 5,
        "value2": 20,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_OUTPUT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller2",
        "message": "Chiller 2 , Eva Output is less than 5°C, more than 20°C",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 44,
        "value1": 5,
        "value2": 20,
        "consecutiveMinute": 1
      },
      {
        "dataType": "POWER_LOADING",
        "deviceType": "CHILLER",
        "deviceName": "Chiller2",
        "message": "Chiller 2, Power Loading is less than 30%",
        "operator": "LESS_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 44,
        "value1": 30,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "ACTIVITY_COUNT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller3",
        "message": "Chiller 3 has more than 6 activities per day",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 45,
        "value1": 6,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "DATA_QUALITY",
        "deviceType": "CHILLER",
        "deviceName": "Chiller3",
        "message": "Chiller 3 Data Rate is below 97%",
        "operator": "LESS_THAN",
        "priority": "LOW",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 45,
        "value1": 97,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EFFICIENCY",
        "deviceType": "CHILLER",
        "deviceName": "Chiller3",
        "message": "Chiller 3 , Efficiency is less than 0.4kW/RT, more than 1kW/RT",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 45,
        "value1": 0.4,
        "value2": 1,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_DELTA",
        "deviceType": "CHILLER",
        "deviceName": "Chiller 3",
        "message": "Chiller 3 , Delta Temp  is more than  7°C",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 45,
        "value1": 7,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_DELTA",
        "deviceType": "CHILLER",
        "deviceName": "Chiller3",
        "message": "Chiller 3 , Delta Temp  is less than  2°C",
        "operator": "LESS_THAN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 45,
        "value1": 2,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_INPUT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller3",
        "message": "Chiller 3 , Eva Input is less than 5°C, more than 20°C",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 45,
        "value1": 5,
        "value2": 20,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_OUTPUT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller3",
        "message": "Chiller 3, Eva Output is less than 5°C, more than 20°C",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 45,
        "value1": 5,
        "value2": 20,
        "consecutiveMinute": 1
      },
      {
        "dataType": "POWER_LOADING",
        "deviceType": "CHILLER",
        "deviceName": "Chiller3",
        "message": "Chiller 3, Power Loading is less than 30%",
        "operator": "LESS_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 45,
        "value1": 30,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "ACTIVITY_COUNT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller4",
        "message": "Chiller 4 has more than 6 activities per day",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 46,
        "value1": 6,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "DATA_QUALITY",
        "deviceType": "CHILLER",
        "deviceName": "Chiller4",
        "message": "Chiller 4 Data Rate is below 97%",
        "operator": "LESS_THAN",
        "priority": "LOW",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 46,
        "value1": 97,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EFFICIENCY",
        "deviceType": "CHILLER",
        "deviceName": "Chiller4",
        "message": "Chiller 4 , Efficiency is less than 0.4kW/RT, more than 1kW/RT",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 46,
        "value1": 0.4,
        "value2": 1,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_DELTA",
        "deviceType": "CHILLER",
        "deviceName": "Chiller 4",
        "message": "Chiller 4 , Delta Temp  is more than  7°C",
        "operator": "GREATER_THAN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 46,
        "value1": 7,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_DELTA",
        "deviceType": "CHILLER",
        "deviceName": "Chiller4",
        "message": "Chiller 4 , Delta Temp  is less than  2°C",
        "operator": "LESS_THAN",
        "priority": "HIGH",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 46,
        "value1": 2,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_INPUT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller4",
        "message": "Chiller 4 , Eva Input is less than 5°C, more than 20°C",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 46,
        "value1": 5,
        "value2": 20,
        "consecutiveMinute": 1
      },
      {
        "dataType": "EVA_OUTPUT",
        "deviceType": "CHILLER",
        "deviceName": "Chiller4",
        "message": "Chiller 4 , Eva Output is less than 5°C, more than 20°C",
        "operator": "BETWEEN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 46,
        "value1": 5,
        "value2": 20,
        "consecutiveMinute": 1
      },
      {
        "dataType": "POWER_LOADING",
        "deviceType": "CHILLER",
        "deviceName": "Chiller4",
        "message": "Chiller 4, Power Loading is less than 30%",
        "operator": "LESS_THAN",
        "priority": "HIGH",
        "frequencyType": "HOUR",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 46,
        "value1": 30,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "DATA_QUALITY",
        "deviceType": "PUMP",
        "deviceName": "Pump1",
        "message": "Pump1 Data Rate is below 97%",
        "operator": "LESS_THAN",
        "priority": "INFO",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 41,
        "value1": 97,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "DATA_QUALITY",
        "deviceType": "PUMP",
        "deviceName": "Pump2",
        "message": "Pump2 Data Rate is below 97%",
        "operator": "LESS_THAN",
        "priority": "INFO",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 42,
        "value1": 97,
        "value2": null,
        "consecutiveMinute": 1
      },
      {
        "dataType": "DATA_QUALITY",
        "deviceType": "PUMP",
        "deviceName": "Pump3",
        "message": "Pump3 Data Rate is below 97%",
        "operator": "LESS_THAN",
        "priority": "INFO",
        "frequencyType": "MINUTE",
        "frequencyValue": 1,
        "active": true,
        "clientId": 13,
        "siteId": 13,
        "deviceId": 43,
        "value1": 97,
        "value2": null,
        "consecutiveMinute": 1
      }
    ]
